# Generated by Django 4.2.2 on 2023-07-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_remerashop', '0002_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
